[manifest]
version = "1.0.0"
priority = -20

[[patches]]
[patches.pattern]
target = "main.lua"
pattern = '''
if love.timer then
    love.timer.sleep(0.1)
end
''' # This is added by smods and can only be found in dumps
position = "before"
payload = '''
WEBSOCKET._client:close()
SMODS.restart_game()
'''
match_indent = true
times = 1
