[manifest]
version = "1.0.0"
priority = -20

[[patches]]
[patches.pattern]
target = "main.lua"
pattern = '''
if love.timer then
    love.timer.sleep(0.1)
end
''' # This is added by smods and can only be found in dumps made by lovely
position = "before"
payload = '''
if G.can_restart then
    G.on_crash_callback()
end
WEBSOCKET._client:close()
'''
match_indent = true
times = 1
